# Generated by Django 4.2.16 on 2024-10-19 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('opponent', models.CharField(max_length=50)),
                ('user_score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('result', models.CharField(choices=[('Win', 'Win'), ('Loss', 'Loss')], default='Win', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
