# Generated by Django 5.0.6 on 2024-12-06 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_match_localtournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='localgame',
            name='dates',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='localtournament',
            name='dates',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
