# Generated by Django 4.2.13 on 2024-06-23 16:43

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/accounts/default.png', max_length=200, upload_to=users.models.GenerateProfileImagePath),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_password_pin',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
    ]
