# Generated by Django 4.2.13 on 2024-06-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar_alter_user_reset_password_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_password_pin',
            field=models.CharField(default='', max_length=6, null=True),
        ),
    ]
