# Generated by Django 5.0.6 on 2024-07-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_reset_password_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_password_pin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
