# Generated by Django 5.0.6 on 2024-07-19 15:47

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=users.models.GenerateDefaultImagePath, max_length=200, upload_to=users.models.GenerateProfileImagePath),
        ),
    ]
