# Generated by Django 5.0.6 on 2024-07-23 14:16

from django.db import migrations, models
import django_countries.fields

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_select',
            field=django_countries.fields.CountryField(default='PS', max_length=2),
        ),
    ]
