# Generated by Django 5.0.6 on 2024-09-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is2faActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otpCheck',
            field=models.BooleanField(default=False),
        ),
    ]
