# Generated by Django 4.2.16 on 2024-10-25 18:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_exp_user_level_user_losses_user_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default=users.models.default_18_years_ago, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otpCheck',
            field=models.BooleanField(default=True),
        ),
    ]
