# Generated by Django 5.0.6 on 2024-07-28 16:45

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=django_bleach.models.BleachField(),
        ),
    ]
