# Generated by Django 5.0.6 on 2024-09-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='followedUser',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlockedUser',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
